# Generated by Django 4.1.3 on 2022-11-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='date_listing_ends',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='date_of_listing',
            field=models.DateField(),
        ),
    ]
